var data = {
  page_title: "Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_bil: "Invoice with our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_cfl: "Manage your Cash Flow with our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_rec: "Manage your Accounts Receivable with our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_inv: "Control your Inventory with our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_csh: "Control your Cash and Debt with our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_prf: "Monitor your Profitability with our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_mnf: "Manifesto of our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_prc: "Pricing of our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_tst: "Testimonials of our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_sig: "Signup for Your Account of our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_gsg: "Getting Started Guide for our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_vid: "Video Tutorials for our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_title_faq: "Frequently Asked Questions about our Simple and Easy to use Management Accounting Software in the Cloud for Small and Medium Businesses",
  page_description: "A simple and easy to use management accounting software that small and medium business owners use in the Cloud to keep their businesses <b>organized and under control</b> with <b>clear and up-to-date accounts</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory and cash flow. Easily export income and expenses reports for your accountant.",
  page_description_bil: "A simple and easy to use management accounting software that small and medium business owners use in the Cloud to invoice and keep their businesses organized and under control with clear and up-to-date accounts. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant",
  page_description_cfl: "A simple and easy to use management accounting software that small and medium business owners use in the Cloud to manage their cash flow and keep their businesses organized and under control with clear and up-to-date accounts. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant",
  page_description_rec: "A simple and easy to use management accounting software that small and medium business owners use in the Cloud to manage their accounts receivable and keep their businesses organized and under control with clear and up-to-date accounts. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  page_description_inv: "A simple and easy to use management accounting software that small and medium business owners use in the Cloud to manage their inventory and keep their businesses organized and under control with clear and up-to-date accounts. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant",
  page_description_csh: "A simple and easy to use management accounting software that small and medium business owners use in the Cloud to keep their businesses cash and debt under control and <b>keep the finances of their businesses in order, clear,and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  page_description_prf: "A simple and easy to use management accounting software that small and medium business owners use in the Cloud to analyze the profitability of their businesses and <b>keep their businesses organized and under control with clear and up-to-date accounts</b. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  page_description_mnf: "Income is vanity, profit is sanity,  and cash flow is king",
  page_description_prc: "Try everything for free for 14 days, pay only for what you need. Total satisfaction or your money back.",
  page_description_tst: "Helping Our Customers Be On Top of their Small and Medium Businesses Finances Since 2005",
  page_description_sig: "Signup for your account today and star keeping your finger in the financial pulse of your business with our management accountinging software",
  page_description_gsg: "The purpose of this guide is to show you the sequence we use to enter the demo company information so that you can understand where it comes from and apply the same logic in the evaluation and implementation of the software in your business.",
  page_description_vid: "A collection of short videos showing what you can do with our management accountinging software",
  page_description_faq: "The most common questions and answers about our management accountinging software",
  notebar_text: "Keep your finger in the financial pulse of Your Business",
  notebar_cta: "Request a demo",
  main_headline: "Unhappy with the Level or Lack of Organization and Control in <br><b>Your Business</b>?",
  main_headline_tst: "Supporting the <b>Financial Control</b> and <b>Decision Making</b> of <b>Small and Medium Businesses</b> since <b>2005</b>",
  main_headline_bil: "Kill Two Birds With One Stone: Modernize Your Invocing and Control the Finances of <b>Your Business</b>",
  main_headline_cfl: "Avoid Nasty Surprises in the Cash Flow of <b>Your Business</b>",
  main_headline_rec: "Make Sure Your Customers <b>Pay All They Owe You</b> on Time",
  main_headline_inv: "Don't Let the Inventory Become a Black Hole in <b>Your Business</b>",
  main_headline_csh: "Control the Cash and Reduce the Cost and Size of the Debt of <b>Your Business</b>",
  main_headline_prf: "Not 100% Sure if <b>Your Business</b> is Really Profitable?",
  main_subheadline: "Solve that problem implementing and using regulary myAbakus",
  main_subheadline_bil: "By creating, sending and managing your invoices in the Cloud with myAbakus",
  main_subheadline_cfl: "By being on top of your outstanding payments with myAbakus",
  main_subheadline_rec: "By keeping your accounts receivable in order and up to date with myAbakus",
  main_subheadline_inv: "By keeping track of all your products changes and inventory with myAbakus",
  main_subheadline_csh: "Reconciling all the cash and debt accounts with the help of myAbaku",
  main_subheadline_prf: "Make sure <b>it is not less profitable than it should be</b> with the help of myAbakus",
  main_description: "A simple and easy to use <b>Management Accounting Software</b> that <b>Small and Medium Business</b> owners use in the <b>Cloud</b> to keep their businesses <b>organized and under control</b> with <b>clear and up-to-date accounts</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_bil: "A simple and easy to use <b>Management Accounting Software</b> that <b>Small and Medium Business</b> owners use in the <b>Cloud</b> to <b>invoice</b> and keep their businesses <b>organized and under control</b> with <b>clear and up-to-date accounts</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_cfl: "A simple and easy to use <b>Management Accounting Software</b> that <b>Small and Medium Business</b> owners use in the <b>Cloud</b> to <b>manage their cash flow</b> and keep their businesses <b>organized and under control</b> with <b>clear and up-to-date accounts</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_rec: "A simple and easy to use <b>Management Accounting Software</b> that <b>Small and Medium Business</b> owners use in the <b>Cloud</b> to <b>manage their accounts receivable</b> and keep their businesses <b>organized and under control</b> with <b>clear and up-to-date accounts</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_inv: "A simple and easy to use <b>Management Accounting Software</b> that <b>Small and Medium Business</b> owners use in the <b>Cloud</b> to <b>manage their inventory</b> and keep their businesses <b>organized and under control</b> with <b>clear and up-to-date accounts</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_csh: "A simple and easy to use <b>Management Accounting Software</b> that <b>Small and Medium Business</b> owners use in the <b>Cloud</b> to <b>keep their cash and debt under control</b> and keep their businesses <b>organized and under control</b> with <b>clear and up-to-date accounts</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_prf: "A simple and easy to use <b>Management Accounting Software</b> that <b>Small and Medium Business</b> owners use in the <b>Cloud</b> to <b>analyze and understand their profitability</b> and <b>keep the finances of their businesses in order, clear,and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory and cash flow. Easily export income and expenses reports for your accountant.",
  benefits_headline: "<b>Simple</b> and <b>Easy</b> to use Management Accounting Software for <b>Small and Medium Businesses Owners</b>",
  features_headline: "Management Accounting Software",
  features_subheadline: "To control and keep your business finances in the right trayectory",
  non_accountants_headline: "Management Management Accounting Software<br> for <b>Non-Accountants</b>",
}
