var data = {
  page_title: "Accounting and Invoicing Software in the Cloud for Small and Medium Businesses",
  page_title_bil: "Invoicing Software for Small and Medium Businesses",
  page_title_cfl: "Cash Flow Software for Small and Medium Businesses",
  page_title_rec: "Accounts Receivable Software for Small and Medium Businesses",
  page_title_inv: "Inventory Software for Small and Medium Businesses",
  page_title_csh: "Accounting and Invoicing Software in the Cloud for Small and Medium Businesses - Cash & Debt",
  page_title_prf: "Accounting and Invoicing Software in the Cloud for Small and Medium Businesses - Profitability",
  page_description: "An Accounting and Invoicing Software in the Cloud that Small and Medium Business owners use to <b>keep their businesses accounts in order, clear, and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory and cash flow. Easily export income and expenses reports for your accountant.",
  page_description_bil: "An Accounting and Invoicing Software in the Cloud that Small and Medium Business owners use to invoice and keep their businesses accounts in order, clear, and up to date. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant",
  page_description_cfl: "An Accounting and Invoicing Software in the Cloud that Small and Medium Business owners use to manage their cash flow and keep their businesses accounts in order, clear, and up to date. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant",
  page_description_rec: "An Accounting and Invoicing Software in the Cloud that Small and Medium Business owners use to manage their accounts receivable and keep their businesses accounts in order, clear, and up to date. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  page_description_inv: "An Accounting and Invoicing Software in the Cloud that Small and Medium Business owners use to manage their inventory and keep their businesses accounts in order, clear, and up to date. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant",
  page_description_csh: "An Accounting and Invoicing Software in the Cloud that Small and Medium Business owners use to keep their businesses cash and debt under control and <b>keep their businesses accounts in order, clear,and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  page_description_prf: "An Accounting and Invoicing Software in the Cloud that Small and Medium Business owners use to analyze the profitability of their businesses and <b>keep their businesses accounts in order, clear, and up to date</b. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  notebar_text: "Keep your finger in the financial pulse of Your Business",
  notebar_cta: "Request a demo",
  main_headline: "Build & Grow YOUR BUSINESS on a Solid Foundation",
  main_headline_bil: "Kill Two Birds With One Stone: Modernize Your Invocing and Get Your Business Accounts Organized",
  main_headline_cfl: "Avoid Surprises in YOUR BUSINESS Cash Flow",
  main_headline_rec: "Make Sure YOUR CUSTOMERS are Paying All they Owe on Time",
  main_headline_inv: "Do not let YOUR BUSINESS Inventory Become a Black Hole",
  main_headline_csh: "Keep an Eye on YOUR BUSINESS Cash and the Size and Costs of its Debt",
  main_headline_prf: "Not 100% Sure How Profitable is YOUR BUSINESS?",
  main_subheadline: "Understanding its finances and controlling its accounts with the help of myAbakus",
  main_subheadline_bil: "By creating, sending and managing your invoices in the Cloud with myAbakus",
  main_subheadline_cfl: "By being on top of your outstanding payments with myAbakus",
  main_subheadline_rec: "By keeping your accounts receivable in order and up to date with myAbakus",
  main_subheadline_inv: "By keeping track of all your products changes and inventory with myAbakus",
  main_subheadline_csh: "Reconciling all the cash and debt accounts with the help of myAbaku",
  main_subheadline_prf: "Make sure <b>it is not less profitable than it should be</b> with the help of myAbakus",
  main_description: "A <b>Practical Accounting</b> and Invoicing Software in the <b>Cloud</b> that <b>Small and Medium Business</b> owners use to <b>keep their businesses accounts in order, clear, and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory and cash flow. Easily export income and expenses reports for your accountxant.",
  main_description_bil: "A <b>Practical Accounting</b> and Invoicing Software in the <b>Cloud</b> that <b>Small and Medium Business</b> owners use to <b>invoice</b> and <b>keep their businesses accounts in order, clear, and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_cfl: "A <b>Practical Accounting</b> and Invoicing Software in the <b>Cloud</b> that <b>Small and Medium Business</b> owners use to <b>manage their cash flow</b> and <b>keep their businesses accounts in order, clear, and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_rec: "A <b>Practical Accounting</b> and Invoicing Software in the <b>Cloud</b> that <b>Small and Medium Business</b> owners use to <b>manage their accounts receivable</b> and <b>keep their businesses accounts in order, clear, and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_inv: "A <b>Practical Accounting</b> and Invoicing Software in the <b>Cloud</b> that <b>Small and Medium Business</b> owners use to <b>manage their inventory</b> and <b>keep their businesses accounts in order, clear, and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_csh: "A <b>Practical Accounting</b> and Invoicing Software in the <b>Cloud</b> that <b>Small and Medium Business</b> owners use to <b>keep their cash and debt under control</b> and <b>keep their businesses accounts in order, clear, and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory, and cash flow. Easily export income and expenses reports for your accountant.",
  main_description_prf: "A <b>Practical Accounting</b> and Invoicing Software in the <b>Cloud</b> that <b>Small and Medium Business</b> owners use to <b>analyze and understand their profitability</b> and <b>keep their businesses accounts in order, clear,and up to date</b>. Manage invoicing, accounts receivable and payable, cash and banks, inventory and cash flow. Easily export income and expenses reports for your accountant.",
  benefits_headline: "<b>Easy</b> Accounting Software for <b>Small and Medium Businesses Owners</b>",
  benefits_subheadline: "Who know that the financial control of their company must be in their hands and is not something they can delegate to an external accountant",
  features_headline: "b>Useful</b> Accounting and Invoicing Software",
  non_accountants_headline: "Accounting Software for <b>Non-Accountants</b>",
}
